CREATE TABLE IF NOT EXISTS COUNTRY_INFO (
    NAME TEXT NOT NULL,
    COUNTRY_CODE TEXT NOT NULL,
    REGEX TEXT NOT NULL,
    PRIMARY KEY (COUNTRY_CODE)
);

INSERT INTO `COUNTRY_INFO` (NAME, COUNTRY_CODE, REGEX) VALUES ('Cameroon','+237','\(237\)\ ?[2368]\d{7,8}$');
INSERT INTO `COUNTRY_INFO` (NAME, COUNTRY_CODE, REGEX) VALUES ('Ethiopia','+251','\(251\)\ ?[1-59]\d{8}$');
INSERT INTO `COUNTRY_INFO` (NAME, COUNTRY_CODE, REGEX) VALUES ('Morocco','+212','\(212\)\ ?[5-9]\d{8}$');
INSERT INTO `COUNTRY_INFO` (NAME, COUNTRY_CODE, REGEX) VALUES ('Mozambique','+258','\(258\)\ ?[28]\d{7,8}$');
INSERT INTO `COUNTRY_INFO` (NAME, COUNTRY_CODE, REGEX) VALUES ('Uganda','+256','\(256\)\ ?\d{9}$	');
